Repository pystardust/ani-cli, pull requests merged in 2021-12, with the labels that each got.

#209 Fix base_url and Fix for video not able to play or download
  ani-cli
Labels: type: bug, category: url, Priority 1: high

#232 Fix regex bug for gogoplay1 link
  ani-cli
Labels: type: bug, category: parsing, Priority 1: high

#190 Allow download without install media player
  ani-cli
Labels: type: enhancement, Priority 2: medium

#234 New Readme
  README.md
Labels: type: enhancement, Priority 2: medium

#236 Updated get_links and fixed get_video_quality function
  ani-cli
Labels: type: bug, category: parsing, Priority 1: high

#239 Fix color formatting on some status messages
  ani-cli
Labels: type: bug, Priority 3: low, category: ui ux

#137 Replace setsid with nohup for mac compatibility
  ani-cli
Labels: type: bug, os: mac, priority 1: high, status: conflicting

#126 Inform user if update is available. Includes instuctions on how to update. Added Git to dependencies.
  Makefile
  README.md
  ani-cli
Labels: type: enhancement, priority 2: medium, category: ui ux, status: conflicting

#143 Add scraping for recent anime
  ani-cli
Labels: type: bug, category: parsing, priority 1: high

#55 Previous/next episode menu works on keypresses
  ani-cli
Labels: type: feature request, priority 4: wishlist, category: ui ux

#121 Change copy to symlink in Makefile
  Makefile
Labels: type: enhancement, priority 3: low, category: qa
