Repository pystardust/ani-cli, pull requests merged in 2022-01, with the labels that each got.

#96 Added flag for specifying download directory
  ani-cli
Labels: type: feature request, priority 4: wishlist, category: ui ux

#248 fix: only update history when video could be played
  ani-cli
Labels: type: bug, priority 2: medium, category: qa

#244 Fix bug on searching anime with special character
  ani-cli
Labels: type: bug, category: parsing, priority 2: medium

#292 Test with shellcheck
  .github/workflows/master.yml
  ani-cli
Labels: type: enhancement, priority 2: medium, category: qa

#308 normal quality doesn't exist
  ani-cli
Labels: type: bug, category: parsing, priority 2: medium

#335 Added a simple check for a null $video_url
  ani-cli
Labels: type: enhancement, priority 3: low, category: qa

#338 switched to vidcdn
  README.md
  ani-cli
Labels: type: bug, category: url, priority 1: high

#256 Support for more players and removal of ampersands
  README.md
  ani-cli
Labels: type: feature request, os: mac, priority 3: low

#352 Improve UX and slim down
  .github/workflows/master.yml
  README.md
  ani-cli
Labels: type: enhancement, priority 3: low, category: ui ux

#367 Reduce scope, expand Linting
  .github/workflows/master.yml
  CONTRIBUTING.md
  README.md
  ani-cli
  disclaimer.md
Labels: type: enhancement, priority 3: low, category: qa

#381 Unite the branches
  Makefile
  README.md
Labels: type: enhancement, priority 2: medium, category: qa

#371 Code cleanup
  CONTRIBUTING.md
  ani-cli
Labels: type: enhancement, priority 3: low, category: qa

#410 Fix makefile to work with latest update #403
  Makefile
Labels: os: android

#414 Replacing jq with regex
  README.md
  ani-cli
Labels: category: parsing

#415 Auto play
  ani-cli
Labels: category: ui ux

#427 Fix #426
  ani-cli
Labels: type: bug

#429 Fix #428
  ani-cli
Labels: type: bug

#440 Fix grep: invalid repetition count(s) regex bug
  ani-cli
Labels: type: bug, category: parsing
