Repository pystardust/ani-cli, pull requests merged in 2022-02, with the labels that each got.

#473 update: shellcheck rule
  CONTRIBUTING.md
Labels: type: enhancement, priority 3: low, category: docs

#471 added so you can select all episodes when you select a range
  README.md
  ani-cli
Labels: type: feature request, priority 4: wishlist, category: ui ux

#462 fix: Adding exit option in search anime menu
  ani-cli
Labels: type: feature request, priority 4: wishlist, category: ui ux

#475 Fix Ani-cli breaks pywal set terminal colors
  ani-cli
Labels: type: bug, priority 2: medium, category: ui ux

#479 Fix invalid number entered bug in history menu
  ani-cli
Labels: type: bug, priority 2: medium

#477 Fix #464
  ani-cli
Labels: type: enhancement, category: ui ux

#481 docs: fixed README
  README.md
Labels: os: mac, category: docs

#485 New Readme head
  README.md
Labels: priority 2: medium, category: docs

#492 Install instructions
  README.md
Labels: category: docs

#490 Fix #482
  README.md
  ani-cli
Labels: type: bug, priority 2: medium, category: ui ux

#494 Fixes for bug #491
  ani-cli
Labels: type: bug, type: enhancement, category: ui ux

#506 docs: added maintainer advice section
  CONTRIBUTING.md
  README.md
Labels: type: feature request, priority 2: medium, category: docs

#520 fix: #504 and other fixes
  ani-cli
Labels: type: enhancement, category: ui ux

#534 docs: updating termux installation, now works with both mpv and vlc (-v option)
  README.md
Labels: category: player, category: docs, os: android

#544 fix : link parsing problems and reduce curl call for majority of animes
  README.md
  ani-cli
Labels: type: bug, type: enhancement, category: url
