Repository pystardust/ani-cli, pull requests merged in 2022-03, with the labels that each got.

#558 Show options for video qualities.
  ani-cli
Labels: priority 3: low, category: ui ux

#554 Fix incompatibility with zsh
  ani-cli
Labels: category: parsing, priority 2: medium

#563 fix: new decrypt function, script working again
  ani-cli
Labels: category: url, priority 1: high

#573 rapid resume
  ani-cli
Labels: category: player
